function [BW,RGB] = createMask_HSV(RGB,HSV,channel1Min,channel1Max)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Copyright 2018-2019 The MathWorks, Inc.

% Auto-generated by colorThresholder app on 30-Jul-2018
%------------------------------------------------------


% Convert RGB image to chosen color space
%HSV = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
% channel1Min = 0.097;
% channel1Max = 0.930;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.000;
channel2Max = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.000;
channel3Max = 1.000;

% Create mask based on chosen histogram thresholds
if channel1Max <= channel1Min
    sliderBW = (HSV(:,:,1) >= channel1Min ) | (HSV(:,:,1) <= channel1Max) & ...
        (HSV(:,:,2) >= channel2Min ) & (HSV(:,:,2) <= channel2Max) & ...
        (HSV(:,:,3) >= channel3Min ) & (HSV(:,:,3) <= channel3Max);
else
    sliderBW = (HSV(:,:,1) >= channel1Min ) & (HSV(:,:,1) <= channel1Max) & ...
        (HSV(:,:,2) >= channel2Min ) & (HSV(:,:,2) <= channel2Max) & ...
        (HSV(:,:,3) >= channel3Min ) & (HSV(:,:,3) <= channel3Max);
end
BW = sliderBW;

% Set background pixels where BW is false to zero.
RGB(repmat(~BW,[1 1 3])) = 0;

end
