function [BW,RGB] = createMask_LAB(RGB,LAB,thresh)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Copyright 2018-2019 The MathWorks, Inc.

% Auto-generated by colorThresholder app on 07-Aug-2018
%------------------------------------------------------


% Convert RGB image to chosen color space
%LAB = rgb2lab(im);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 10.048;
channel1Max = 96.621;

% Define thresholds for channel 2 based on histogram settings
channel2Min = thresh(1);
channel2Max = thresh(2);

% Define thresholds for channel 3 based on histogram settings
channel3Min = -15.271;
channel3Max = 55.062;

% Create mask based on chosen histogram thresholds
sliderBW = (LAB(:,:,1) >= channel1Min ) & (LAB(:,:,1) <= channel1Max) & ...
    (LAB(:,:,2) >= channel2Min ) & (LAB(:,:,2) <= channel2Max) & ...
    (LAB(:,:,3) >= channel3Min ) & (LAB(:,:,3) <= channel3Max);
BW = sliderBW;

if nargout == 2    
    % Set background pixels where BW is false to zero.
    RGB(repmat(~BW,[1 1 3])) = 0;
end

end
